# Generated by Django 2.2.1 on 2019-07-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catdasoccerplayer',
            name='team_number',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
